// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgLx9sr-VzdWuGx0V5Mv7R37kaPLFHRw4',
    appId: '1:997733560424:android:283164ced09db1654f8bdd',
    messagingSenderId: '997733560424',
    projectId: 'flutter-proyect-d19cc',
    databaseURL: 'https://flutter-proyect-d19cc-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-proyect-d19cc.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbtPi0yjwzBncpW-VLDTpggsnbY6rMLdc',
    appId: '1:997733560424:web:f50e9f6d30e6710b4f8bdd',
    messagingSenderId: '997733560424',
    projectId: 'flutter-proyect-d19cc',
    authDomain: 'flutter-proyect-d19cc.firebaseapp.com',
    databaseURL: 'https://flutter-proyect-d19cc-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-proyect-d19cc.firebasestorage.app',
    measurementId: 'G-1RLE8SNWMX',
  );
}
